name: .NET

on:
  push:
    paths: 'Backend/**'
  pull_request:
    branches:
      - develop
      - main
      - 'release/*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Unit Tests
      run: dotnet test Backend
